### ISSUE TITLE
[Question]If a interface used memory cache the request.timing().responseEnd ‘s  value is always  same.

### ISSUE THREAD

**Issue by RaymoneZhang** [microsoft/playwright-java#1080]
helllo，I find if a interface used memory cache then  I use page.reload() and collect the requests's info . then I find two question.

the first question is the interface used memory cache  ,I  view the interface  in devtools（ f12） , the time is 0ms.then view the request.timing().responseEnd in playwright .It shows dozens of milliseconds.
I'm confused why caused the dozens of milliseconds.
![image](https://user-images.githubusercontent.com/45260643/192272013-4a72551a-7c5a-4cbe-9689-49ea18b19a2d.png)
![image](https://user-images.githubusercontent.com/45260643/192273270-840ae1fd-dc8e-4773-9479-aee4b08c02b9.png)
![image](https://user-images.githubusercontent.com/45260643/192272990-be1e8958-779e-48f8-a85d-9292f01ff0f1.png)

the second question is  if Used the page.reload and the interface used memory cache  . I find the value of request.timing().responseEnd is the same. No matter how many times the page is refreshed.

![image](https://user-images.githubusercontent.com/45260643/192276031-326f9dfd-5a4d-43f6-9597-572e2b910c70.png)

I sincerely look forward to your answer. thank you.

**Comment by yury-s** [comment]
This is a bug, we cannot trust the regular network timing data when resource is served from memory cache as it contains some stale data (which is why it's the same on every reload). DevTools resets it to 0 in the UI when the request is served from memory. We should set requestStart/responseStart/responseEnd to -1 when the request is served from memory.
