### ISSUE TITLE
Cant we convert locator(multiple elements) to a Java Stream ?

### ISSUE THREAD

**Issue by siva994** [microsoft/playwright-java#1084]
If I need to do an action on a Locator(Multiple elements) , I need to locatorObj.nth(index), which always asks for a for loop . 

When we have have Java Stream from 1.8 , why should I again use for loop ?Instead cant I convert it to a Stream object and use it for my action on multiple webelements?

**Using for iteration :**
 for (int i = 0; i <multiple.count() ; i++) {
            multiple.nth(i).click();
        }

**Using Stream (Not supported currently)**

 Stream.of(multiple).forEach((s)->s.click());

**Comment by yury-s** [comment]
You can write a helper method `StreamOf` that does the iteration internally and converts it to a stream, note that the number of locators can change over time and and also the element returned by the .nth(i) can change (e.g. because the page changes after you click on one of the locators). We have a few methods that address cases where you may need to query multiple nodes: [Locator.allTextContents()](https://playwright.dev/java/docs/api/class-locator#locator-all-text-contents), [Locator.allInnerTexts()](https://playwright.dev/java/docs/api/class-locator#locator-all-inner-texts), [Locator.elementHandles()](https://playwright.dev/java/docs/api/class-locator#locator-element-handles).

What is the problem you are trying to solve?

**Comment by yury-s** [comment]
Closing as part of the triage process, feel free to open a new issue if the above reply doesn't work for you.
