### ISSUE TITLE
[BUG] Incorrect JAVA_HOME in Dockerfile

### ISSUE THREAD

**Issue by mushycode** [microsoft/playwright-java#1103]
**Context:**
- Playwright Version: 1.27
- Operating System: Linux
- Browser: Chromium
- Extra: ARM64 arch

**JAVA_HOME was not updated after the JDK version was updated to 17.**

[Link to the issue
](https://github.com/microsoft/playwright-java/blob/release-1.27/utils/docker/Dockerfile.focal#L21)

We can easily override the ENV while running the image, but it looks like the change was missed out.

**Comment by yury-s** [comment]
Yeah, we should update that to point to jdk 17 instead. It turns out that maven 3.6.4 that comes with ubuntu 22.04 will fail with jre 17 and if we only ship jdk 17 we'll have to also install new version of Maven  (3.8.6) from Apache downloads. It may be easier to just switch to ubuntu 22.04 as bas image.
