### ISSUE TITLE
[BUG] Corrupted channel by directly writing to native stream in forked JVM 

### ISSUE THREAD

**Issue by kucharzyk** [microsoft/playwright-java#1149]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Linux (Fedora)
- Browser: All

**Code Snippet**

```java
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/shardis/dev/projects/java-studio-hub/target/surefire-reports/2022-12-23T00-15-56_946-jvmRun1.dumpstream
[INFO] 
```

**Describe the bug**

I am getting warning about corrupted channel from surefire after building the project with playwright test.

I think that streams written to native stream might be just warnings like: ```BEWARE: your OS is not officially supported by Playwright; downloading fallback build.``` but it might be something more.

Description of this warning on maven site: 
https://maven.apache.org/surefire/maven-failsafe-plugin/faq.html#corruptedstream

**Comment by yury-s** [comment]
It looks like Surefire plugin has made an interesting design decision to use stdout/stderr instead of creating a dedicated pipe for IPC communication with its child process and it assumes that all writes to the standard output of the process that runs the tests go through System.out/err. This is not the case when you use Playwright - all the stderr/stdout messages from the driver process launched by Playwright Java library are forwarded to its stdout/stderr fd's of the test process which makes the plugin unhappy. Thankfully, according to the [plugin documentation](https://maven.apache.org/surefire/maven-surefire-plugin/examples/process-communication.html)  you can configure the plugin to use TCP/IP for the communication by simply adding this to the plugin's config:

```xml
<configuration>
  <forkNode implementation="org.apache.maven.plugin.surefire.extensions.SurefireForkNodeFactory"/>
</configuration>
```
Will that work for you?

**Comment by kucharzyk** [comment]
@yury-s I can confirm that changing surefire configuration have solved the problem.

Warning message is now gone. Thanks for your help.
