### ISSUE TITLE
[Feature] waitForEvent("dialog")

### ISSUE THREAD

**Issue by ortoniKC** [microsoft/playwright-java#1153]
Hi, In Playwright-TS, we have a function - page.waitForEvent("Dialog");
it will wait for the dialog (JS Alert), unfortunately, it is missing in Playwright-JAVA.

Why it is required?
To achieve explicit wait for an alert.

Sample code:

```
package org.example;

import com.microsoft.playwright.*;
import java.nio.file.Paths;

public class WebKitScreenshot {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(true));
      Page page = browser.newPage();
      page.navigate("https://letcode.in/waits");
      page.onDialog(dialog -> {
          System.out.println(dialog.message());
          dialog.accept();
      });
      page.locator("id=accept").click();
      page.waitForTimeout(6_000);
    }
  }
}

```
Expected: I want to achieve the same but without waitForTimeout.
 

Created this request as per the conversation with Max.
https://playwright.slack.com/archives/CSUHZPVLM/p1671698876739829

**Comment by yury-s** [comment]
The dialogs are modal and must be handled synchronously within `onDialog` listener, otherwise subsequent calls to playwright API may hang because the page is blocked on the modal dialog and cannot handle any events. E.g. if click triggers navigation and a modal dialog then the following call would hang:

```java
Dialog dialog = page.waitForDialog(() -> page.getByText('submit').click());
```
Ideally, we'd remove `waitForEvent('dialog')` in node.js too but that ship has sailed.

Re: your question about waiting for a dialog, you can do something like this:

```java
    boolean[] didShowDialog = {false};
    page.onDialog(dialog -> {
      System.out.println(dialog.message());
      dialog.accept();
      didShowDialog[0] = true;
    });
    page.locator("id=accept").click();
    while (!didShowDialog[0]) {
      page.waitForTimeout(100);
    }
```
