### ISSUE TITLE
Allow configuring timeout for installing browsers

### ISSUE THREAD

**Issue by bitspittle** [microsoft/playwright-java#1226]
I'm using playwright in my project, and a user just hit this timeout indirectly:

https://github.com/microsoft/playwright-java/blob/2db2762a0d145c322c80dc6f51c08b915b725e04/driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java#L94

Given that other areas of the codebase are configurable (i.e. https://playwright.dev/docs/test-timeouts), I'm wondering if it would be possible to configure this timeout as well?

Thanks!

**Comment by bitspittle** [comment]
Alternately, maybe the code can throw a more specific exception type, so I can catch it and recover?

**Comment by yury-s** [comment]
We could probably make it configurable but I'm a bit skeptical about it. 10 minutes is quite a lot, perhaps the download just gets stuck for some reason. Do you know if it's because of a very slow connection or there was a trmporary issue with our CDN ? You can see some logs by running playwright with `DEBUG=pw:install`

**Comment by bitspittle** [comment]
Honestly, I can respect the choice to not make it configurable. That said, if it was configurable, I might set the timeout much lower than 10 minutes *and* add retries :)

Alternatively, if you threw a specific exception rather than a runtimeexception, I might be able to catch it in my code and inform the user about what happened. At the same time, I can understand if the team intentionally wants it to be a runtime exception, something that's not ever expected to happen normally.

---

Let me explain what I'm doing, as a concrete use case to consider...

* I have a project which is a web framework library *and* a CLI program that runs your web server plus other commands. 
* One of the commands for the CLI is `export`, which basically takes your web app and snapshots html output for each route the user has registered.
* The `export` command delegates to Playwright.
* A new user tried using my program, and when they ran the `export` command, it just hung for a while, before crashing after 10 minutes.
* They tried using the program again later and it worked.

Some things I'd like to do, if possible:

* [optional] Show updates to users to let them know stuff is downloading (with % complete)
* Retry automatically if the download fails (possibly informing the user each time a retry starts)
* Handle the exception thrown by Playwright, so I can tell the user what happened and what they can try to do next (probably just "try again later"). That would at least be a better experience than showing them a callstack.

Thanks for taking a look at my issue! I don't consider it urgent. Let me know if you had any other questions.

**Comment by yury-s** [comment]
Thanks for providing more context!

> Retry automatically if the download fails (possibly informing the user each time a retry starts)

We already do retry browser download internally, each time from a different CDN (up to 3). This should cover most of the outages, which is why I was surprised it just hung for 10 minutes.

> [optional] Show updates to users to let them know stuff is downloading (with % complete)

This is already done. E.g. when running a playwright test you should see something like this in the output:

```
[INFO] Running com.microsoft.playwright.TestClick
[INFO] Downloading Chromium 111.0.5563.64 (playwright build v1053) from https://playwright.azureedge.net/builds/chromium/1053/chromium-linux.zip
[INFO] |■■■■■■■■                                                                        |  10% of 143.5 Mb
[INFO] |■■■■■■■■■■■■■■■■                                                                |  20% of 143.5 Mb
```
Note that it includes the CDN url and will print extra messages if the download fails. Which Playwright version are you on?

> Handle the exception thrown by Playwright, so I can tell the user what happened and what they can try to do next (probably just "try again later"). That would at least be a better experience than showing them a callstack.

We've made a decision to stay away from checked exception and adopt approach similar to javascript where all playwright exception are implement by one class. It should be fairly safe to just look at [the error message](https://github.com/microsoft/playwright-java/blob/2db2762a0d145c322c80dc6f51c08b915b725e04/driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java#L97) (we don't change that text normally) if you want to provide a better message to the user. Would that work?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by bitspittle** [comment]
Ah, sorry I never replied. I'm OK with closing this.

I definitely had a bunch of users hitting this error by the way (probably users overseas if I had to guess?). I since updated my code to only download the Chromium browser at export, instead of all of them, and that seems to have helped a lot. I haven't gotten any reports since then.

I was surprised this was so tricky to do. It would be really nice to have a way to tell Playwright to only grab this or that browser straight from the Java APIs. Instead, I had to use Java to kick off the CLI to do the initial download myself and then set the "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD" to "1" env variable using playwright options. I don't think I'm the only one who wants to only download some of the browsers, not all of them.
