### ISSUE TITLE
record and play error in java playwright waiting until "load" not oping site[BUG]

### ISSUE THREAD

**Issue by Anoopkumarjoshi** [microsoft/playwright-java#1279]
### System info
- Playwright Version: 1.32.0
- Operating System: [All, Windows 10 etc.]
- Browser: [All, Chromium, Firefox, WebKit]

### Source code
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen srt-in-extrazone.startek.com/logon/LogonPoint/"

**Comment by yury-s** [comment]
Looks like a Chromium issue, launching `'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --user-data-dir=bbb srt-in-extrazone.startek.com/logon/LogonPoint/` doesn't load the page.

Also starting Chromium with `'/Users/yurys/Library/Caches/ms-playwright/chromium-1060/chrome-mac/Chromium.app/Contents/MacOS/Chromium' --user-data-dir=ddd srt-in-extrazone.startek.com/logon/LogonPoint/`  won't load the page either. Typing the URL manually after the browser loaded sometimes work sometimes hangs the same way.

**Comment by yury-s** [comment]
The loading often hangs for me even if pasting that link in the browser. However, changing it to `https://srt-in-extrazone.startek.com/logon/LogonPoint/index.html` works fine:

```sh
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen https://srt-in-extrazone.startek.com/logon/LogonPoint/index.html"
```

Closing as this is a problem with the web site (and might be the browser) rather than Playwright. If you believe this is a Playwright problem please file a new issue with a self contain example (which doesn't depend on the behavior of a third-party server).
