### ISSUE TITLE
[Feature] Ability to build a Docker image with the Node and browsers downloaded in advance

### ISSUE THREAD

**Issue by vemv** [microsoft/playwright-java#1296]
Hi!

I'm attempting to using playwright-java for a production use case.

I noticed that downloading browsers is delayed until playwright-java is actually used for the first time, at runtime.

That would presumably make that first production request slower. The downloading/installation itself is also subject to fail, for a variety of reasons.

Therefore it seems desirable to build Docker images with the Browsers, as well as Node, already in it.

Probably it would help if the directory for such downloads was stable - my understanding is that currently those are tmp files, and therefore not suitable for Dockerfile scripting.

---

I'm aware of `Dockerfile.jammy`. I may use it for the time being, however it would seem desirable to provide the building blocks for users to craft their own Dockerfiles.

Thanks - V

**Comment by yury-s** [comment]
Each playwright version goes with fixed browser builds and the build numbers have to match that of the docker image in order to avoid downloads. It looks like you are using docker image 1.34.0 with some old playwright version as Playwright 1.34 is shipped with chromium-1064.

The docker files are open source and you can adjust them to your liking.
