### ISSUE TITLE
[Question] How to await/resolve `Deferred<Void> page.waitForTimeout()` method?

### ISSUE THREAD

**Issue by Microtribute** [microsoft/playwright-java#202]
I am trying to log in to a web page and take a certain set of actions using Playwright. Once the LOGIN button is click the browser takes me to the dashboard. And I need to certain actions on the reporting page. So my code goes like this:

```java

// Sign in
Browser = playwright.chromium().launch();

final Page page = context.newPage();

// Navigate to the SIGNIN page
page.navigate("https://www.example.com/signin");

// Fill in the username
page.fill("#username", "foo");

// Fill in the password
page.fill("#password", "password");


// Click the LOGIN button
page.click("button[type='submit']");

// Once the LOGIN button is clicked you will be taken to the Dashboard page
// and you can navigate to the reporting page from here.
// Make sure the browser navigates to the dashboard by waiting for 10 seconds
page.waitForTimeout(10000);

// Navigate to the reporting page.
page.navigate("https://www.example.com/reporting");

page.fill("#date1", "2020-11-20");
page.fill("#date2", "2021-01-08");
```

However, when I do this, the `page.waitForTimeout(10000)` does not wait for 10 seconds. and the code continues to run without waiting. How can I make it actually wait?

**Comment by yury-s** [comment]
> However, when I do this, the page.waitForTimeout(10000) does not wait for 10 seconds. and the code continues to run without waiting. How can I make it actually wait?

This API was indeed confusing as you'd have to call `.get()` on the returned object. I tried to address that in #188, now `waitForTimeout()` will block further execution for the specified amount of time. The change is available in `0.180.0-SNAPSHOT` so you can give it a try.

However, if you just need to wait for the navigation initiated by the click to finish `page.click()` does it automatically (see [this section](https://playwright.dev/docs/navigations#auto-wait-1) for more details). In some scenarios where the navigation is triggered asynchronously you may need to use `page.futureNavigation()` but in most common cases you won't need it. If you need to wait for a particular element on the page to become visible after navigation playwright will do it automatically too. What I'm trying to say is that you should probably use a less flaky and more performant mechanism instead of waitForTimeout.
