### ISSUE TITLE
[Question] is it possible to only download desired browser?

### ISSUE THREAD

**Issue by LawrenceZ** [microsoft/playwright-java#215]
rather than download all 3 browsers, is there a way to download only the one that you want to use? e.g. playwright-chromium

**Comment by mxschmitt** [comment]
Not yet, there is an upstream issue for it to get more feedback, the best is to upvote that: https://github.com/microsoft/playwright/issues/3866

**Comment by LawrenceZ** [comment]
> Not yet, there is an upstream issue for it to get more feedback, the best is to upvote that: [microsoft/playwright#3866](https://github.com/microsoft/playwright/issues/3866)

Thank you! Hope it will get added soon!

**Comment by yury-s** [comment]
@LawrenceZ  There is no counterpart of playwright-chromium for java at the moment. Can you tell us more about your use case and why there is a need to download just one browser?

**Comment by LawrenceZ** [comment]
@yury-s one of the use cases I'm experimenting is to use playwright in a aws lambda function (e.g. w/ only chromium), so to simulating some web actions?

**Comment by yury-s** [comment]
The image is likely to be too heavy for AWS lambda without extra effort even if you install only one browser, so more work will need to be done to strip off unused parts and compress the image to meet the requirements. With that said, [`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` ](https://playwright.dev/java/docs/installation#skip-browser-downloads) environment variable allows to skip browser download step, if you preinstall the browser to the cache (`mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install chromium"` will download just one browser) in your image and pass the env variable it should work.

**Comment by yury-s** [comment]
Closing per the last comment and considering that we don't have immediate plans to support other ways for single-browser downloads.

**Comment by mjaggard** [comment]
I also want this.
Use case:
I render HTML to PDF using Chromium in our system and would like to avoid downloading all the browsers on developer machines which the auto download is very useful for.

**Comment by yury-s** [comment]
Does the approach from the comment above work for you?

**Comment by mjaggard** [comment]
No, it requires developers to do more to setup their machines, which I like to avoid

**Comment by Aldaviva** [comment]
I faced the same challenge where I didn't want extra steps on the development and deployment machines to restrict which browsers to install.

I solved this with my own subclass of `com.microsoft.playwright.impl.Driver` and implementation of `com.microsoft.playwright.Playwright` so that I could pass additional arguments to the forked `playwright.cmd install` invocation. Instead of `com.microsoft.playwright.impl.DriverJar.installBrowsers()` forking `playwright.cmd install`, my `installBrowsers()` method has been overloaded with an optional collection of browser names to install. This can fork something like `playwright.cmd install chromium`, which is [how you tell the JavaScript-based Playwright library to just install Chromium instead of installing every browser](https://playwright.dev/docs/cli#install-browsers). The end result is that I can call the following factory method to get a `Playwright` instance, and it will only download Chromium and ffmpeg.
```java
try (Playwright playwright = CustomPlaywrightImpl.create("chromium")) { /* ... */ }
```

Importantly to me, all of this browser installation behavior is now encapsulated in my single JAR file, and it doesn't require any extra environment variables, script invocations, or installation procedures no matter where I copy and run that JAR. It also retains the existing auto-updating and cleanup logic from Playwright that I find useful.

I had to copy a fair amount of unchanged code from `DriverJar` and `PlaywrightImpl` to get the private access I needed without using reflection, but it's been working well for me on two personal projects so far. There are a couple of alternative approaches I also came up with, but this one seemed the simplest to me.

Feel free to look at or copy my code from [Aldaviva/twitter-favorites](https://github.com/Aldaviva/twitter-favorites/tree/master/src/main/java/com/microsoft/playwright/impl) if it's helpful to you. It currently compiles with Playwright 1.12.1. It also includes some additional code for passing extra environment variables to the JS process, which I acknowledge has also been added to the mainline Playwright Java library since I wrote these classes.

**Comment by anthonyalayo** [comment]
Is there any workarounds for this in 2023?

**Comment by YuryAlsheuski** [comment]
Just use PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 env variable

**Comment by anthonyalayo** [comment]
@YuryAlsheuski

> Just use PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 env variable

Does that still allow my program to download the binary when I do something like this?

```
        var playwright = Playwright.create();
        playwright.firefox()...
```

The ideal scenario from the developer perspective would be to only download the binary that we need when it is called.

**Comment by helpermethod** [comment]
> @YuryAlsheuski
> 
> > Just use PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 env variable
> 
> Does that still allow my program to download the binary when I do something like this?
> 
> ```
>         var playwright = Playwright.create();
>         playwright.firefox()...
> ```
> 
> The ideal scenario from the developer perspective would be to only download the binary that we need when it is called.

I doubt that this is possible. In your CI you can install the desired browsers using jbang/mvn install and then skip the installation when running the tests.

**Comment by k1w1m8** [comment]
Per https://playwright.dev/java/docs/browsers playwright can now install single browser.

The issue now is that playwright-java DriverJar installBrowsers() doesn't allow the browser name parameter to be passed to "install".

Any plans to fix this?

**Comment by yury-s** [comment]
`DriverJar` is not a part of public API. You can install a single browser in java by a combination of PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD and then installing the browsers [via CLI](https://playwright.dev/java/docs/browsers#install-browsers).

Please use new issues for new bug reports, we usually don't monitor closed bugs.

**Comment by k1w1m8** [comment]
Yes, in fact, that is exactly what I did. Thanks. 

Would be nice if the Java API included that natively, but we have a relatively easy workaround.

**Comment by Aldaviva** [comment]
I found a cleaner way than my previous technique above to pass extra arguments, like a browser name to install, when the Playwright Java library executes `node cli.js install`. It's less invasive and brittle than before, and therefore easier to upgrade to newer versions of Playwright.

I have packaged it into a [shared library](https://github.com/Aldaviva/playwright-extra-install-arguments) and [published it on Maven Central](https://central.sonatype.com/artifact/com.aldaviva.playwright/playwright-extra-install-arguments) if anyone else wishes to use it.

```java
ExtraInstallArgumentsDriver.activate();
CreateOptions createOptions = ExtraInstallArgumentsDriver.setExtraInstallArguments("chromium --with-deps --only-shell");
Playwright playwright = PlaywrightImpl.create(createOptions);
```
