### ISSUE TITLE
[Question] Would it be possible to share a browser between different threads?

### ISSUE THREAD

**Issue by drrodio** [microsoft/playwright-java#241]
Hi there, we are very excited about this development

We have several tasks to do with many urls from different websites, my question is if we can have several browsers with several tasks and interact with them from different threads. It would be great that a thread operates in a tab of a shared browser. I think it's not possible because of https://github.com/microsoft/playwright-java#is-playwright-thread-safe

Is there any option to do it? Any ideas?

Thanks a lot for your answer

**Comment by yury-s** [comment]
This is not currently supported. We intentionally would like to parallelize at the browser process level, i.e. single java thread controls single browser process (many contexts/pages could be created in that process if needed and they may communicate with each other). If one needs to split their test suite and run some tests in parallel it could be achieved by splitting the test suite in N groups, creating a thread per group and then on each thread creating its own Playwright instance and a new browser. Each of the threads is supposed to create one browser process and then reuse it between all tests running on that thread. As long as the browsers is launched once per group of tests rather than once per test it should provide enough savings and flexibility. We've been following same approach in other languages (javascript, python) and didn't see any issues so far, so we'd like to keep it simple unless there is an evidence that it doesn't work.

**Comment by drrodio** [comment]
Thanks for the answer @yury-s, the only problem I see with this scenario is that you loose the parallelism because the java calls to nodejs are synchronous, so for each playwright instance you can only do an operation at a time. Anyway, it seems far enough for common cases

Kind regards!

**Comment by yury-s** [comment]
True, this is more limited compared to what you can do with promises and async/await in Node.js playwright client as there one can at least issue multiple requests at the same time. We may reconsider current approach in the future and allow running several commands in parallel similar to JavaScript. At the moment we don't see strong evidences that it would be necessary and that the extra complexity of the APIs would be justified.
