### ISSUE TITLE
[Question] Docker image on docker hub

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [microsoft/playwright-java#270]
Hi do you have published docker image for playwright java? Or i should build it by my own?

**Comment by arkasandr** [comment]
@ocherniavskyi-lohika-tix i try to biuld my docker image for starting spring-boot app, but have some problems with missing dependencies
`Caused by: com.microsoft.playwright.impl.ServerException: Error: Host system is missing dependencies!
`
using Dockerfile from this repositoriy didn't solve my problem. May be @yury-s can help us.

**Comment by mxschmitt** [comment]
Did you use an Ubuntu image as your base image? Then also these dependencies needs to be installed: https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.focal That would explain this error message.

**Comment by arkasandr** [comment]
@mxschmitt thanks! I'm using https://github.com/microsoft/playwright-java/blob/master/Dockerfile.focal  and all dependencies from it are installed. But my list of missing libraries include another dependencies:

` Caused by: com.microsoft.playwright.impl.ServerException: Error: Host system is missing dependencies!
myr-bot   | 
myr-bot   |   Missing libraries are:
myr-bot   |       libgobject-2.0.so.0
myr-bot   |       libglib-2.0.so.0
myr-bot   |       libatk-1.0.so.0
myr-bot   |       libatk-bridge-2.0.so.0
myr-bot   |       libgio-2.0.so.0
myr-bot   |       libdrm.so.2
myr-bot   |       libxkbcommon.so.0
myr-bot   |       libXcomposite.so.1
myr-bot   |       libXdamage.so.1
myr-bot   |       libXfixes.so.3
myr-bot   |       libXrandr.so.2
myr-bot   |       libgbm.so.1
myr-bot   |       libgtk-3.so.0
myr-bot   |       libgdk-3.so.0
myr-bot   |       libpango-1.0.so.0
myr-bot   |       libcairo.so.2
myr-bot   |       libgdk_pixbuf-2.0.so.0
myr-bot   |       libatspi.so.0
myr-bot   |       libxshmfence.so.1
myr-bot   | 
myr-bot   | Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
myr-bot   |        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:139)
myr-bot   |        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:123)
myr-bot   |        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:86)
myr-bot   |        ... 23 common frames omitted
`

**Comment by ocherniavskyi-lohika-tix** [comment]
@arkasandr not reproduced in my case, but it would be great if docker publication will be triggered each release

**Comment by ocherniavskyi-lohika-tix** [comment]
@arkasandr fyi my host os is based on Ubuntu 20.14

**Comment by arkasandr** [comment]
@ocherniavskyi-lohika-tix sorry, may be I can find and see your Dockerfile somewhere? I show my file here 
[https://github.com/microsoft/playwright-java/issues/263#issuecomment-776144611](url)

**Comment by ocherniavskyi-lohika-tix** [comment]
@arkasandr im using default Dockerfile.focal

**Comment by ocherniavskyi-lohika-tix** [comment]
We are moving from my initial question, is there any plans to provide docker images on docker hub?

**Comment by yury-s** [comment]
@ocherniavskyi-lohika-tix yes, we are planning to publish docker images on https://mcr.microsoft.com/ which will make them available on Docker Hub. For now you can build image from source.

**Comment by yury-s** [comment]
Docker image is now available on Docker Hub. Latest release based on Ubuntu 20.04 is 'mcr.microsoft.com/playwright/java:focal', you can find other published tags on [this page](https://mcr.microsoft.com/v2/playwright/java/tags/list).
