### ISSUE TITLE
[Question] Custom Element Implementation

### ISSUE THREAD

**Issue by chaganiu** [microsoft/playwright-java#349]
What is the best practice to implement a custom element.  For example, we have a combobox that isn't a normal html select option.  There are certain workarounds for how to select an option.

I was thinking about implementing the `ElementHandle` interface and passing in the page and the locator for the root element.  Something like this:

```java
public class CustomComboBox implements ElementHandle {
  private ElementHandle elementHandle;

  public CustomComboBox(Page page, String selector) {
    this.elementHandle = page.querySelector(selector);
  }
}
```

For all of the methods i would just pass on the method call to the `elementHandle`.  And for the `selectOption` methods I would implement the custom logic needed to select an option in this custom combobox.

Is there a better way to do this?

**Comment by yury-s** [comment]
First of all, all interfaces in the API except for callbacks are expected to be implemented only by Playwright. You should consider them as `final` classes (e.g. one shouldn't try to implement `Page` interface). We use interfaces for the API definition primarily for documentation purposes and to hide implementation noise from the clients eyes. Furthermore, Playwright code makes certain assumptions about the actual implementation of the interfaces and if you provide your own class implementing `ElementHandle` and then try to pass it e.g. as an argument into [`Page.evaluate`](https://playwright.dev/java/docs/api/class-page?_highlight=evaluate%28#pageevaluateexpression-arg) it will be serialized as a JSON object rather than as an element handle which is not what you want.

Can you elaborate on why do you need to implement `ElementHandle`  rather than just wrap it into your own `CustomComboBox` class and delegating some of the calls to the corresponding handle?
```java
public class CustomComboBox {
  private ElementHandle elementHandle;

  public CustomComboBox(Page page, String selector) {
    this.elementHandle = page.querySelector(selector);
  }

  public select(String value) {
    // some logic actually selecting the value
  }
}
```
If you want to have generic code that works on collections of element handles and custom elements it might be easier to have your own hierarchy that either delegates directly to the wrapped handle or does some tricky logic and calls into playwright when needed. I'd like to better understand you constraints.

**Comment by chaganiu** [comment]
this would work for me, thank you.

**Comment by chaganiu** [comment]
@yury-s is there a way to make this generic enough so I can use a `Page` or `Frame` to find and interact with elements?

**Comment by yury-s** [comment]
For the methods that are present both on Page and Frame you can normally use `Page` and `Page.mainFrame()` interchangeably (if you look at the implementation those methods simply delegate to the main frame anyway). You can also have an overloaded constructor like this:

```java
public class CustomComboBox {
  private ElementHandle elementHandle;

  public CustomComboBox(Page page, String selector) {
    this(page.mainFrame(), selector);
  }


  public CustomComboBox(Frame frame, String selector) {
    this.elementHandle = frame.querySelector(selector);
  }
}
```

**Comment by chaganiu** [comment]
@yury-s i have it overloaded and it works for getting the initial element but to find other elements that may not be necessarily under the main ElementHandle (so I can't use `elementHandle.querySelector`) I would still need to know whether to do `Page.xxx` or `Frame.xxx`.  

I'm not sure if it's relevant but i retrieve the Frame object like this:

```java
    public Frame GetContentFrame() {
        var frameSelector = "#contentFrame";
        var frameHandle = page.querySelector(frameSelector);
        return frameHandle.contentFrame();
    }
```

**Comment by yury-s** [comment]
You need to know the Frame in which to lookup the other element, then you can get access to that frame e.g. via `Page.frame(name)` and call `frame.waitForSelector` on it.
