### ISSUE TITLE
Issues in Docker on RaspberryPi: Exec format error

### ISSUE THREAD

**Issue by YNedderhoff** [microsoft/playwright-java#399]
Should this work on my raspberry pi?

Something that works perfectly fine locally on my MacBook Pro fails with this in Docker on my RaspberryPi:

```
2021-04-16 07:34:14,375 INFO  [x.n.impftermincheckermilk.Main] - Started Main in 15.468 seconds (JVM running for 18.505)
/tmp/playwright-java-12603370371329365042/playwright.sh: 3: /tmp/playwright-java-12603370371329365042/playwright.sh: /tmp/playwright-java-12603370371329365042/node: Exec format error
/tmp/playwright-java-12603370371329365042/playwright.sh: 3: /tmp/playwright-java-12603370371329365042/playwright.sh: /tmp/playwright-java-12603370371329365042/node: Exec format error
java.io.EOFException
	at com.microsoft.playwright.impl.ReaderThread.readIntLE(PipeTransport.java:94)
	at com.microsoft.playwright.impl.ReaderThread.readMessage(PipeTransport.java:122)
	at com.microsoft.playwright.impl.ReaderThread.run(PipeTransport.java:109)
```

The base image I use is `adoptopenjdk/openjdk11:jre-11.0.8_10-debian`. I am picky about the base image, as I need to be able to build it on several architectures, especially my MacBook Pro as well my RaspberryPi 4.

**Comment by mxschmitt** [comment]
Playwright is currently not supported on a Raspberry PI, see this issue for reference: https://github.com/microsoft/playwright/issues/4984

**Comment by YNedderhoff** [comment]
Is it possible to get this to work myself, as this person apparently did for python?
https://github.com/microsoft/playwright/issues/4984#issuecomment-799752932

Or is it impossible?

**Comment by yury-s** [comment]
> Is it possible to get this to work myself, as this person apparently did for python?
> [microsoft/playwright#4984 (comment)](https://github.com/microsoft/playwright/issues/4984#issuecomment-799752932)
> 
> Or is it impossible?

What is missing is basically the driver (think node.js playwright) build that would work in that image which in turn requires browsers running on that architecture (should not be a problem for chromium).  It is certainly possible but requires dedicated effort which is not a priority for us at the moment. Since there are no plans to fix this in the near future I'm going to close this issue, please vote for the [upstream one](https://github.com/microsoft/playwright/issues/4984) so that we could prioritize it higher.

**Comment by YNedderhoff** [comment]
Thanks. I hope the upstream one will at least be considered, even though it is closed already.
