### ISSUE TITLE
[QUESTION] Can the bundled chromium downloaded along with playwright lib be used in production?

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#485]
Hi,
I am planning to use playwright to serve requests for printing pdf from html documents.

Is it safe/preferred to use the bundled chromium browser that is preinstalled along with playwright library to serve production traffic?

 Or Should I prefer downloading/ managing stable chromium binaries seperately?

I can see in the documentation that it is the latest build of chromium browser that is bundled with playwright. Is it the stable build as well?

**Comment by yury-s** [comment]
> Is it safe/preferred to use the bundled chromium browser that is preinstalled along with playwright library to serve production traffic?
> 

It is safe to use the bundled version and we expect that to be the default choice. It is usually built from the recent Chromiun sources, it doesn't include proprietary features - only open source stuff.

> Or Should I prefer downloading/ managing stable chromium binaries seperately?

It depends on your requirements, if you need to test against some features that are available only in the proprietary builds (e.g. codecs) or you have a product requirement to test against a particular version of Chrome you may prefer to manage official build download, otherwise it's totally fine to use bundled build. It would be less hassle to use the bundled binaries.
