### ISSUE TITLE
[Question] setLocale is not working

### ISSUE THREAD

**Issue by jyoti-c** [microsoft/playwright-java#486]
Here's the code to change the locale to English India for Google Drive. If you check the screenshot generated the language is still English UK 
```java
BrowserContext context = browser.newContext(new NewContextOptions()
              .setLocale("en-IN"));
Page page = context.newPage();
page.route("**", route -> {
  System.out.println(route.request().url());
  route.resume();
});
page.navigate("https://drive.google.com/");
Page newpage = context.waitForPage(()->page.click("xpath=//div[@class='drive__hero-buttons']//a[contains(text(),'Go to Drive')]"));
newpage.waitForLoadState();
newpage.type("#identifierId","invalis");
newpage.waitForResponse("**",()->  newpage.press("#identifierId","Enter"));
newpage.screenshot(new Page.ScreenshotOptions().setPath(Paths.get("screenshot-" + browserType.name() + ".png")));
```

**Comment by yury-s** [comment]
I don't know what the page should be in en-IN, the problem likely has to do with the Drive localization (it might be that it just falls back to English for en-IN). It works fine with other locales, e.g. I tried with 'fr-CH' and the login page was in French:

![image](https://user-images.githubusercontent.com/9798949/122111248-5b181d80-cdd4-11eb-8670-bb0eb550f8c4.png)

If you think that it's because playwright doesn't properly override one of the locale-specific APIs in the browser please tell us which one, otherwise it seems that the problem is just how the drive page handles that particular locale.
