### ISSUE TITLE
[Question]: Possible to have multiple concurrent pages?

### ISSUE THREAD

**Issue by H4xX0r1337** [microsoft/playwright-java#535]
### Your question

In PlaywrightSharp (C#), the entire api is async, allowing for using multiple pages concurrently. In java, this seems to be different.
The library is also not thread safe.
Is there still any way to use multiple pages in a single browser concurrently?

**Comment by yury-s** [comment]
> Is there still any way to use multiple pages in a single browser concurrently?

You can open multiple pages in the same browser and each of them may have some asynchronous activity.  Since Playwright API is synchronous you can only interact with one of the pages at any given point in time. This is deliberate design choice. We expect playwright/browser instances to be used as unit of parallelization as described [here](https://playwright.dev/java/docs/multithreading).

Does this not work for you for some reason?

**Comment by H4xX0r1337** [comment]
@yury-s The link you sent uses multiple browsers and multiple playwright instances. I don't understand how this is supposed to be in the same browser. 

Also, does "you can only interact with one of the pages at any given point in time" include the automatic delays? If yes, then it is almost entirely unusable for parallelization.

**Comment by yury-s** [comment]
> @yury-s The link you sent uses multiple browsers and multiple playwright instances. I don't understand how this is supposed to be in the same browser.
> 

"We expect playwright/browser instances to be used as unit of parallelization" which is why they use different browsers for parallel tests. Nothing prevents you from creating several pages in each of those browsers if need be but interaction with each browser will be synchronous as you already noted.

> Also, does "you can only interact with one of the pages at any given point in time" include the automatic delays?

Yes, it does.

> If yes, then it is almost entirely unusable for parallelization.

This is a strong statement :grin: By design we parallelize on the browser level not within a browser. What are you trying to achieve?

**Comment by H4xX0r1337** [comment]
@yury-s so you should make multiple browsers to be truly parallel? that would be pretty resource wasteful.
