### ISSUE TITLE
[Feature]: New Option for custom driver path

### ISSUE THREAD

**Issue by aarushiag** [microsoft/playwright-java#564]
### Feature request

Can we get a documented mechanism for providing a custom driver path to Playwright ? As per the discussion - https://github.com/microsoft/playwright-java/issues/556 , we can currently use the property - "playwright.cli.dir" to define the custom path. However, it would be ideal if there can be formal mechanism to provide the same (since this is undocumented and may change in future)

**Our use case**
We have a requirement of installing playwright java within Linux Alpine Image. On some testing, it was found that the node.js binary (used for running the driver) that is shipped along playwright will not work on Alpine (because Playwright is built against libc while Alpine works with musl). To make it work, it was suggested that we should extract the driver to another custom directory and replace the node executable with a compatible one. Using this workaround, playwright was successfully installed on Linux Alpine. 

This can definitely help others who have a similar use case making playwright java compatible to Linux Alpine.

**Comment by mxschmitt** [comment]
Alpine can't work, because our browsers only build on Ubuntu 18 and Ubuntu 20. You are probably interested in this to use the Java language binding inside Alpine without the driver and have the browsers running somewhere else where all the dependencies are satisfied: https://github.com/microsoft/playwright/issues/4687

In theory you could swap the Node.js executable with a Node.js optimised for Alpine, then you could use a Chromium which you can get via the Alpine package manager and set this as an executable path, but this is not officially supported. (WebKit and Firefox won't work since they are custom built).

Relates: https://github.com/microsoft/playwright/issues/1986

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still encounter issues.
