### ISSUE TITLE
[Question] Can I limit Chromium memory ?

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#579]
### Your question

Hello, 
Can I limit Chromium memory ? I run some Chromium used too much memory.

**Comment by yury-s** [comment]
Make sure you close `BrowserContext` after you are done with it. Playwright will hold some resources (e.g. network data) until the context is closed. Apart from that if the page you are loading makes the browser use too much memory it's something to be fixed in the page's code. Can you explain what kind of limit you want to set?
