### ISSUE TITLE
[Bug]: `waitForConsoleMessage` should honor `WaitForConsoleMessageOptions.predicate`

### ISSUE THREAD

**Issue by CarterLi** [microsoft/playwright-java#594]
### Playwright version

1.14.1

### Operating system

Windows, MacOS, Linux

### What browsers are you seeing the problem on?

Chromium, Firefox, WebKit

### What happened? / Describe the bug

There was an option `predicate` in `WaitForConsoleMessageOptions`

https://github.com/microsoft/playwright-java/blob/a171c3960117f652522755abbb9b0e321a615f49/playwright/src/main/java/com/microsoft/playwright/Page.java#L2457

However we didn't use it

https://github.com/microsoft/playwright-java/blob/696610de15cc218d93d83dc155945ccc48dce195/playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java#L460

Only `WaitForConsoleMessageOptions.timeout` was used, while `WaitForConsoleMessageOptions.predicate` wasn't

**Comment by CarterLi** [comment]
waitForConsoleMessage is designed strangely. Since it accept a callback `Runnable code`

https://github.com/microsoft/playwright-java/blob/696610de15cc218d93d83dc155945ccc48dce195/playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java#L452

I was expecting that waitForConsoleMessage was non-blocking, and would return immediately. But after some testing I found that waitForConsoleMessage did block.

That makes the callback `Runnable code` completely useless. And because the interface `Runnable` accepts no arguments, we cannot even know what message was printed.

On the other hand, there is no overload which doesn't need a callback. And if you pass null as the callback, NPE is thrown.

**Comment by yury-s** [comment]
> There was an option `predicate` in `WaitForConsoleMessageOptions`

This is a bug, I will prepare a fix shortly.

> waitForConsoleMessage is designed strangely. Since it accept a callback `Runnable code`

The callback is expected to run an action that triggers the event (see [this page](https://playwright.dev/java/docs/events#waiting-for-event) with examples). E.g.
```java
    ConsoleMessage message = page.waitForConsoleMessage(() -> {
      page.evaluate("setTimeout(() => console.log(1), 1000)");
    });
    System.out.println(message.text());
```

> I was expecting that waitForConsoleMessage was non-blocking, and would return immediately. But after some testing I found that waitForConsoleMessage did block.

`waitForConsoleMessage` will block until the message is received that's the whole point, if you need non-blocking listeners you can use [`onConsoleMessage`](https://playwright.dev/java/docs/api/class-page#page-event-console) instead.

> On the other hand, there is no overload which doesn't need a callback. And if you pass null as the callback, NPE is thrown.

You can always pass an empty callback `page.waitForConsoleMessage(() -> {})` if the event is triggered asynchronously. In most of the cases this usually indicates a race condition since the console message event may have fired by the time you start waiting for it, that't the rationale for always requiring `Runnable action` argument.
