### ISSUE TITLE
[ISSUE] waitForURL behavior depends on parameter type...?

### ISSUE THREAD

**Issue by HittiGubbi** [microsoft/playwright-java#604]
I was receiving timeout errors whenever trying to use [Page.waitForURL](https://playwright.dev/java/docs/api/class-page#page-wait-for-url). In the end I looked up the source code implementation and noticed that the variant taking a String-url combines it whith the base url of the current page:

```
@Override
  public void waitForURL(String url, WaitForURLOptions options) {
    waitForURL(new UrlMatcher(page.context().baseUrl, url), options);
  }
```
Whereas e.g. the variant taking url as a Pattern just uses it directly:

```
@Override
  public void waitForURL(Pattern url, WaitForURLOptions options) {
    waitForURL(new UrlMatcher(url), options);
  }
```

As a consequence I changed page.waitForURL("url_string_parameter") into page.waitForURL(Pattern.compile("url_string_parameter")) and the recurring problem related to timeout errors went away. Is this kind of difference in behavior done on purpose?

The API docs could also give a little bit more information about how the URL matching actually works. I e.g. had to look at the source code to find out that the url parameter to wairForURL is considered to match if it occurs anywhere inside the navigated url.

**Comment by yury-s** [comment]
> As a consequence I changed page.waitForURL("url_string_parameter") into page.waitForURL(Pattern.compile("url_string_parameter")) and the recurring problem related to timeout errors went away.

This is because `page.waitForURL("url_string_parameter")` is equivalent to `page.waitForURL(Pattern.compile("^url_string_parameter$"))`, i.e. exact match of full url string whereas your pattern looks for a substring.

> Is this kind of difference in behavior done on purpose?

Yes.

> The API docs could also give a little bit more information about how the URL matching actually works.

The documentation reads: "A glob pattern, regex pattern or predicate receiving [URL] to match while waiting for the navigation.". I.e. in this case it is a `glob` pattern. I'll update the docs to clarify that passing a string which is not a glob implies that expected url is equal to the string.
