### ISSUE TITLE
[Question] How to catch Response event for iframe?

### ISSUE THREAD

**Issue by chuanhhoang** [microsoft/playwright-java#672]
I know we can catch response event with page.onResponse(). Is there any way to catch response events for iframes?

**Comment by yury-s** [comment]
Which Playwright version is this? Can you also run with `DEBUG=pw:protocol` and upload the log?

**Comment by yury-s** [comment]
It's unclear why you don't see the initial requests to the server but you may be missing image response because you use Thread.sleep(). Replace it with `page.waitForTimeout(100000);` to see the responses that come after the click. This is a known limitation of the synchronous API in Java version of Playwright: messages from the driver are only dispatched when there is an active call of one of the Playwright API methods.

**Comment by chuanhhoang** [comment]
@yury-s You are genius. Thread.sleep was the problem. 
Thank you for your help.
