### ISSUE TITLE
Dockerfile for playwright-java

### ISSUE THREAD

**Issue by joeyfromnijmegen** [microsoft/playwright-java#70]
Thanks again for creating this awesome project. 👏 

Do you guys happen to have a Dockerfile for playwright-java ? or any tips on how I can create one  ?

**Comment by mxschmitt** [comment]
Hi, what would be the core requirements of the Docker image? Its hard to use [official one](https://hub.docker.com/_/openjdk) because its based on Debian which is not fully supported with Playwright (WebKit headless on Debian won't work).

So a custom Ubuntu docker image with the dependencies and Java would be probably how this could be achieved. Like its done in Python: https://github.com/microsoft/playwright-python/blob/master/Dockerfile.

How important is the Java version for you?

**Comment by kumaraditya303** [comment]
@mxschmitt PR on the way for the Docker image 🚀 , should maven install the jar or build from source because if we go the jar way then 4 jars would be needed to copied and installer whereas building from source is easier and after building it would be cleaned. What's your suggestion?

**Comment by yury-s** [comment]
As of #97 there is now a [Dockerfile](https://github.com/microsoft/playwright-java/blob/master/Dockerfile.focal) based on Ubuntu 20.04. Please file new issues if you need any changes to it.
