### ISSUE TITLE
[BUG] Service is unable to recover if the temporary driver-directory gets removed

### ISSUE THREAD

**Issue by Pyppe** [microsoft/playwright-java#728]
**Context:**
- Playwright Version: 1.17.0
- Operating System: Linux
- Browser: All

**Describe the bug**

Playwright uses a `/tmp` directory for creating the driver directory:

https://github.com/microsoft/playwright-java/blob/8d84afccec214856852fd812aa26a50e88e1f9e7/driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java#L31-L34

However, if this directory gets removed, the service will not recover from the situation, but instead all attempts to launch a new browser will fail:

```
Caused by: java.io.IOException: Cannot run program "/tmp/playwright-java-16255647668257527045/playwright.sh": error=2, No such file or directory
```

I'm filing this as a bug because I would argue it should be safe to remove old files from the `/tmp` directory. We encountered this issue, because [tmpreaper](https://manpages.ubuntu.com/manpages/bionic/man8/tmpreaper.8.html) removed the driver directory after seven days.

I think ideally the service should create a new temporary directory if the old one gets removed. Also, it might be beneficial to be able to configure where these driver directories are created?

**Comment by yury-s** [comment]
This is by design. Here are some details on how it works. Platform-specific driver binary (Node.js + node modules) is distributed in a jar file. In order to launch the driver we unpack it first into a temporary directory and then launch it from there. This step happens only once when you launch playwright. When the process finishes the temporary directory will be automatically removed. Playwright expects the the temp files that it creates to stay intact while it is running.

> I'm filing this as a bug because I would argue it should be safe to remove old files from the `/tmp` directory. We encountered this issue, because [tmpreaper](https://manpages.ubuntu.com/manpages/bionic/man8/tmpreaper.8.html) removed the driver directory after seven days.
> 
According to you description the tool removes files that are still in use by a running application which sounds wrong to me (btw, was Playwright running for >7 days?)

> I think ideally the service should create a new temporary directory if the old one gets removed.

This is too much hassle. Imagine the directory being removed from under your feet, if some of the files are still open by the application they won't be removed while others will. Then the application may keep running until it tries to access another file from the driver which has been deleted. We considered providing a way to install driver as separate step independently from Maven and avoid using temp dir altogether, but so far the approach of bundling it in a jar has been working well enough. If we wanted to avoid the temp dir problem we'd rather require preinstalling the driver (see this feature request: https://github.com/microsoft/playwright-java/issues/467).

> Also, it might be beneficial to be able to configure where these driver directories are created?

Yes, but again that seems inferior to just preinstalling the driver as a separate step whereas today maven handles all the dependencies and doesn't require any manual steps.

**Comment by Pyppe** [comment]
Yes; by default `tmpreaper` deletes files that haven't been touched for seven days. And our JVM process had been running for over seven days.

> Yes, but again that seems inferior to just preinstalling the driver as a separate step whereas today maven handles all the dependencies and doesn't require any manual steps.

You could offer the possibility to override the temp-dir e.g. via some predefined system property (such as `-Dplaywright.tmpdir=/path/to/somewhere`)... 🤷

The fact is, as it stands now, you cannot have a long-running Playwright process running on a system where there is some clean-up script (such as `tmpreaper`) cleaning old files from the `/tmp` directory — unless you override the `java.io.tmpdir` (which is what we did). But overriding `java.io.tmpdir` affects **ALL** other library calls (not just Playwright), so it might not be ideal for every use-case.

Anyway... I do realize this is a minor issue. And probably not affecting many users. Just stating that (IMHO) *ideally* the service shouldn't become unusable if some cleaner-script deletes file old files from the temp directory. :) And I also realize, the ROI for fixing this might be quite small. :) Feel free to close this issue, if need be; I won't be offended. 😁

**Comment by yury-s** [comment]
> You could offer the possibility to override the temp-dir e.g. via some predefined system property (such as `-Dplaywright.tmpdir=/path/to/somewhere`)...

I guess this doesn't hurt, adding `playwright.driver.tmpdir` in the linked PR, should be available in the next release. If there are more requests about similar issues we can do something better but it sounds like it will unblock you for now.
