### ISSUE TITLE
[Question]Which of the following configurations of playwright can reduce performance and memory usage?

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#744]
I have a requirement to use the playwright script to test the page performance. The script repeatedly obtains the page interface performance data by entering the page or performing certain operations. Due to the limitation of the machine performance, a maximum of eight performance test scripts can be concurrently executed at a time. Are there any good suggestions for running more scripts concurrently without increasing machine performance?

**Comment by yury-s** [comment]
If your goal is to launch more browsers concurrently it may be easier to do in nodejs version of playwright due to the different threading model. I don't what your current bottleneck with java is and what kind of tests you perform, it's hard to give specific advice without that knowledge. Java API is designed in a way that you normally would have a playwright instance per thread. If you want to orchestrate multiple browsers/pages from each thread you should minimize the time spent in API calls which maybe achieved by reducing timeouts for the methods and changing navigations to wait until [commit](https://playwright.dev/java/docs/api/class-page#page-goto) instead of later stages.
