### ISSUE TITLE
[Feature] LocatorAssertions.setDefaultTimeout()

### ISSUE THREAD

**Issue by N1ro** [microsoft/playwright-java#842]
Hello everyone,

I'd like to request a change for `LocatorAssertions.setDefaultTimeout() `

Why?
Currently, assertions are performed like below with `setTimeout`, we'd like to know if its possilbe to add `LocatorAssertions.setDefaultTimeout()` so we can setup locationAssertions timeout globallly as its possible with `BrowserContext` and `Page` classes, otherwise we'd have to do it individually like so in the below example.

`assertThat(page.locator(  <some locator> ))
            .hasText( expectedMessage, new LocatorAssertions.HasTextOptions().setTimeout( 30000 ) );`
            

Please let us know if you need more info.
           
 Thanks
 Niro

**Comment by chaganiu** [comment]
I just ran into this myself.  one of our apps is slow and the page/browsercontext default timeouts work fine but fail with locator assertions because they take longer than 5 seconds.  This causes us to either write `LocatorAssertions.HasTextOptions().setTimeout( 30000 )` over and over or we have to add

`locator.waitFor()` before asserting.
