### ISSUE TITLE
[Question] How do we poll for some seconds if an element will become present? 

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright-java#918]
Hello,

Can somebody help me with code example of the following situation:

I have a question form on which there could be follow up question depending on the answer of the first question.

So my issue is that I want to poll for let say 3 seconds if an element will become available after a click.

A saw that locator.isVisible timeout option is DEPRECATED, so how do we do it now?

**Comment by yury-s** [comment]
If you know that the element should become visible the recommended way is to use [web-first assertion](https://playwright.dev/java/docs/next/test-assertions#locator-assertions-to-be-visible):
```java
assertThat(page.locator(".my-element")).isVisible();
```
Otherwise you can do a generic poll using [page.waitForTimeout](https://playwright.dev/java/docs/next/api/class-page#page-wait-for-timeout) like this:
```java
    Instant start = Instant.now();
    while (!locator.isVisible() && Duration.between(start, Instant.now()).getSeconds() < 3) {
      page.waitForTimeout(100);
    }
```
In the next version we may introduce generic `poll` method to simplify code like this.

**Comment by NikkTod** [comment]
Hi @yury-s, thanks for the hints.

Usually I use web-first assertions, but they are not returning Boolean.

There are cases where I do not know if this element will become available, so I am using for example an if statement.

e.g. -> if (element.IsVisible) do something.

But as we know .isVisible() is returning immediately, so we need some time to wait for it. 

Will try the waitForTimeout, but having generic poll method will be great.

Thanksss!

**Comment by mxschmitt** [comment]
Closing since we have web-first assertions for that.
